### ISSUE TITLE
UnicodeDecodeError while running main.py

### ISSUE THREAD

**Issue by mattish91** [facorazza/Passwords2Bitwarden#2]
reciving this wile trying to run my zip.  

As i have no clue exactly what this means i can't really resolve it :/ 

`PS C:\Playground\Passwords2Bitwarden> python main.py .\NC-Passwords.zip
Traceback (most recent call last):
  File "C:\Playground\Passwords2Bitwarden\main.py", line 77, in <module>
    cli()
  File "C:\Users\matti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\matti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Playground\Passwords2Bitwarden\main.py", line 48, in cli
    for row in reader:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\csv.py", line 111, in __next__
    row = next(self.reader)
          ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3316: character maps to <undefined>`

Also im trying to run this on my Windows 10 machine, Nextcloud lang set to English, and my computer as well (By natural choice). 

Any clue how to solve it since im looking forward to using my Vaultwarden machine instead of NC Passwords. 😁

**Comment by facorazza** [comment]
Could you please test the code in the branch [2-unicodedecodeerror-while-running-mainpy](https://github.com/facorazza/Passwords2Bitwarden/tree/2-unicodedecodeerror-while-running-mainpy)

**Comment by facorazza** [comment]
@mattish91 Were you able to solve this?

**Comment by flowingice** [comment]
I had similar error, `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 719: character maps to <undefined>` that got fixed by that branch. Import from dump.json into vaultwarden worked fine.

Using Python 3.10.10 on Win 10

**Comment by facorazza** [comment]
That's good I'll close this one

> I had similar error, `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 719: character maps to <undefined>` that got fixed by that branch. Import from dump.json into vaultwarden worked fine.
> 
> Using Python 3.10.10 on Win 10

Thank you for the comment!
